//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Administration_System_v2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admissoin_Time_Fees_Yearly
    {
        public string Admission_Fees_ID { get; set; }
        public string Admission_Student_ID { get; set; }
        public Nullable<decimal> Admisson_Fee { get; set; }
        public Nullable<decimal> Development_Fee { get; set; }
        public Nullable<decimal> Maintainance_Fee { get; set; }
        public Nullable<decimal> Library_Fee { get; set; }
        public Nullable<decimal> Medical_Fee { get; set; }
        public Nullable<decimal> IDCard_Fee { get; set; }
        public Nullable<decimal> Late_Fine { get; set; }
        public Nullable<System.DateTime> Receipt_Print_Time { get; set; }
        public Nullable<System.DateTime> Transaction_Time { get; set; }
        public string Remarks { get; set; }
    
        public virtual Admission_Student Admission_Student { get; set; }
    }
}
