//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Administration_System_v2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admission_Student()
        {
            this.Admission_Exam_Result = new HashSet<Admission_Exam_Result>();
            this.Admissoin_Time_Fees_Yearly = new HashSet<Admissoin_Time_Fees_Yearly>();
            this.Images = new HashSet<Image>();
            this.Students = new HashSet<Student>();
        }
    
        public string Admission_Student_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Full_Name { get; set; }
        public string Gender { get; set; }
        public string Fathers_Name { get; set; }
        public string Mothers_Name { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Blood_Group { get; set; }
        public string Country { get; set; }
        public string Religion { get; set; }
        public string Admission_Session { get; set; }
        public string Current_School { get; set; }
        public string Current_Grade { get; set; }
        public string Interested_Grade { get; set; }
        public string Group { get; set; }
        public Nullable<System.DateTime> Registered_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_Exam_Result> Admission_Exam_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admissoin_Time_Fees_Yearly> Admissoin_Time_Fees_Yearly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
