//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Administration_System_v2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string Inventory_ID { get; set; }
        public string Printer { get; set; }
        public string Computer { get; set; }
        public string Mouse { get; set; }
        public string Keyboard { get; set; }
        public string Projector { get; set; }
        public string Camera { get; set; }
        public string Whiteboard { get; set; }
        public string Marker { get; set; }
        public string Pencil { get; set; }
        public string Clock { get; set; }
        public string Paperbundle { get; set; }
        public string Pen { get; set; }
        public string Duster { get; set; }
        public string Geometrybox { get; set; }
        public string Ruler { get; set; }
        public string Chair { get; set; }
        public string Bench { get; set; }
        public string Table { get; set; }
    }
}
