//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Administration_System_v2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regular_Fees
    {
        public string Regular_Fees_ID { get; set; }
        public Nullable<decimal> Monthly_Fee { get; set; }
        public Nullable<decimal> Exam_Fee { get; set; }
        public Nullable<decimal> Late_Fine { get; set; }
    }
}
