//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Administration_System_v2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Admission_Exam_Result = new HashSet<Admission_Exam_Result>();
            this.Admission_Exam_Result1 = new HashSet<Admission_Exam_Result>();
            this.Images = new HashSet<Image>();
            this.Teacher_Task = new HashSet<Teacher_Task>();
        }
    
        public string Teacher_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Full_Name { get; set; }
        public string Gender { get; set; }
        public string Fathers_Name { get; set; }
        public string Mothers_Name { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Marital_Status { get; set; }
        public string Blood_Group { get; set; }
        public string Country { get; set; }
        public string Religoin { get; set; }
        public string Recruited_Session { get; set; }
        public string Group { get; set; }
        public string Designation { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Status_Time_From { get; set; }
        public Nullable<System.DateTime> Status_Time_To { get; set; }
        public Nullable<System.DateTime> Last_Login_Date { get; set; }
        public string Pasword { get; set; }
        public Nullable<System.DateTime> Joined_Date { get; set; }
        public Nullable<System.DateTime> Resigned_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_Exam_Result> Admission_Exam_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_Exam_Result> Admission_Exam_Result1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher_Task> Teacher_Task { get; set; }
    }
}
